power <- read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?")
febpower <- subset(power,power[1]=="1/2/2007"|power[1]=="2/2/2007")
png("plot1.png", width=480, height=480)
hist(febpower$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
dev.off()